services:

  sdq-api-rust:
    build:
      context: ..
      dockerfile: Dockerfile.rust
    image: sdq-api-rust
    container_name: sdq-api-rust
    networks:
      - sdq
    profiles:
      - api-rust
    environment:
      SDQ_DATABASE_HOST: ${APPLICATION_NAME}-db:5432
      SDQ_DATABASE_NAME: ${SDQ_DATABASE_NAME}
      SDQ_DATABASE_USERNAME: ${SDQ_DATABASE_USERNAME}
      SDQ_DATABASE_PASSWORD: ${SDQ_DATABASE_PASSWORD}
    ports:
      # Required when running the UI in dev mode on top of the service in docker
      - "8081:3000"
    depends_on:
      sdq-db-migration:
        condition: service_completed_successfully

  sdq-service:
    build:
      context: ..
      dockerfile: Dockerfile.java
    image: sdq-app
    container_name: sdq-app
    networks:
      - sdq
    profiles:
      - api-java
    environment:
      SDQ_DATABASE_URL: jdbc:postgresql://${APPLICATION_NAME}-db:5432/${SDQ_DATABASE_NAME}
      SDQ_DATABASE_USERNAME: ${SDQ_DATABASE_USERNAME}
      SDQ_DATABASE_PASSWORD: ${SDQ_DATABASE_PASSWORD}
    ports:
      # Required when running the UI in dev mode on top of the service in docker
      - "8080:8080"
    depends_on:
      sdq-db-migration:
        condition: service_completed_successfully

  sdq-db-migration:
    build:
      context: ../sdq-database
    image: sdq-db-migration
    container_name: sdq-db-migration
    networks:
      - sdq
    environment:
      LIQUIBASE_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://sdq-db:5432/${SDQ_DATABASE_NAME}
      LIQUIBASE_COMMAND_USERNAME: ${SDQ_DATABASE_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${SDQ_DATABASE_PASSWORD}
    depends_on:
      sdq-db:
        condition: service_healthy

  sdq-db:
    image: postgres:17
    container_name: sdq-db
    networks:
      - sdq
    environment:
      POSTGRES_USER: ${SDQ_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SDQ_DATABASE_PASSWORD}
      POSTGRES_DB: ${SDQ_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - sdq_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${SDQ_DATABASE_USERNAME} -d ${SDQ_DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  sdq:
    driver: bridge

volumes:
  sdq_data:
