services:

  sdq-test-db:
    image: postgres:17
    container_name: sdq-test-db
    networks:
      - sdq-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testPassword123
      POSTGRES_DB: sdq
    ports:
      - "5435:5432"
    volumes:
      - sdq_test_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U test -d sdq
      interval: 10s
      timeout: 3s
      retries: 3

  sdq-test-db-migration:
    build:
      context: ../sdq-database
    image: sdq-db-migration
    container_name: sdq-test-db-migration
    networks:
      - sdq-test
    environment:
      LIQUIBASE_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://sdq-test-db:5432/sdq
      LIQUIBASE_COMMAND_USERNAME: test
      LIQUIBASE_COMMAND_PASSWORD: testPassword123
    depends_on:
      sdq-test-db:
        condition: service_healthy

networks:
  sdq-test:
    driver: bridge

volumes:
  sdq_test_data:
