services:

  sdq-service:
    image: sdq-app
    container_name: sdq-app
    networks:
      - sdq
    profiles:
      - include-app
    environment:
      SDQ_DATABASE_URL: jdbc:postgresql://${APPLICATION_NAME}-db:5432/${SDQ_DATABASE_NAME}
      SDQ_DATABASE_USERNAME: ${SDQ_DATABASE_USERNAME}
      SDQ_DATABASE_PASSWORD: ${SDQ_DATABASE_PASSWORD}
      OAUTH2_ISSUER_URI: http://${APPLICATION_NAME}-auth.${LOCAL_STACK_HOST}.nip.io:8085/realms/ratracejoe
      CLIENT_ID: ${SDQ_CLIENT_ID}
      CLIENT_SECRET: ${SDQ_CLIENT_SECRET}
    ports:
      # Required when running the UI in dev mode on top of the service in docker
      - "8080:8080"
    depends_on:
      auth-healthcheck:
        condition: service_completed_successfully
      sdq-db-migration:
        condition: service_completed_successfully

  sdq-db-migration:
    image: sdq-db-migration
    container_name: sdq-db-migration
    networks:
      - sdq
    environment:
      LIQUIBASE_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://${APPLICATION_NAME}-db:5432/${SDQ_DATABASE_NAME}
      LIQUIBASE_COMMAND_USERNAME: ${SDQ_DATABASE_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${SDQ_DATABASE_PASSWORD}
    depends_on:
      sdq-db:
        condition: service_healthy

  sdq-db:
    image: postgres:17
    container_name: sdq-db
    networks:
      - sdq
    environment:
      POSTGRES_USER: ${SDQ_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SDQ_DATABASE_PASSWORD}
      POSTGRES_DB: ${SDQ_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - sdq_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${SDQ_DATABASE_USERNAME} -d ${SDQ_DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

  auth-db:
    image: postgres:17
    container_name: sdq-auth-db
    networks:
      - sdq
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - sdq_auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: ${KEYCLOAK_DATABASE_ROOT_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -U ${KEYCLOAK_DATABASE_USERNAME} -d ${KEYCLOAK_DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

  auth:
    image: quay.io/keycloak/keycloak:22.0
    container_name: sdq-auth
    networks:
      - sdq
    command: start-dev --import-realm --http-port 8080 --health-enabled true
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth-db:5432/${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./auth/:/opt/keycloak/data/import/:ro

  auth-healthcheck:
    image: curlimages/curl:latest
    container_name: auth-healthcheck
    networks:
      - sdq
    depends_on:
      - auth
    entrypoint: "curl --retry 24 --retry-delay 5 --max-time 120 --retry-connrefused http://auth:8080/health/ready"

networks:
  sdq:
    driver: bridge
    ipam:
      config:
        - subnet: ${LOCAL_STACK_CIDR}

volumes:
  sdq_data:
  sdq_auth_data:
