set dotenv-load := true

DB_MODULE := env_var("DB_MODULE")
APP_MODULE := env_var("APP_MODULE")
UI_MODULE := env_var("UI_MODULE")
APPLICATION_NAME := env_var("APPLICATION_NAME")
SDQ_DATABASE_NAME := env_var("SDQ_DATABASE_NAME")
SDQ_DATABASE_USERNAME := env_var("SDQ_DATABASE_USERNAME")

# Default task
default: docker-start-app

# Install UI dependencies
install-ui:
    npm install --prefix {{UI_MODULE}}

# Build the user interface
build-ui: install-ui
    npm run build --prefix {{UI_MODULE}}

# Copy the static resources of the UI into the public backend folder.
copy-ui: build-ui
    rm -rf {{APP_MODULE}}/src/main/resources/static
    cp -R sdq-ui/dist {{APP_MODULE}}/src/main/resources/static

# Run the service via gradle
run-service-dev:
    ./gradlew :spring-app:bootRun

# Build the UI and Run the service via gradle
run-dev: copy-ui run-service-dev

# Build the JAR file
run-build-jar:
    ./gradlew :spring-app:bootJar

# Build the UI and bundle into application JAR file
build-jar: copy-ui run-build-jar

# Runs the user interface in hot reloading mode.
run-ui-dev: install-ui
    npm run dev --prefix {{UI_MODULE}}

# Run the backend unit tests
gradle-run-tests:
    ./gradlew :spring-app:test

# Run the dependencies required by unit tets
docker-run-test-deps:
    docker compose -f local/docker-compose.test.yaml up -d

# Run the unit tests, which depends on us running containers
run-tests: docker-run-test-deps gradle-run-tests

# Run the entire system up within Docker
docker-start-app:
    docker compose -f local/docker-compose.yaml --profile include-app up --build -d

# Run the app dependencies in docker, but not the app itself
# Use run-service-dev for that
docker-run-deps:
    docker compose -f local/docker-compose.yaml up -d

# Stop any docker containers relating to this application
docker-stop:
    docker compose -f local/docker-compose.yaml --profile include-app down
    docker compose -f local/docker-compose.test.yaml --profile include-app down

# Build the Docker image for the application
docker-build-app:
    docker build -t sdq-app .

# Build the Docker image for the database migration
docker-build-db-migration:
    docker build -t sdq-db-migration {{DB_MODULE}}/.

# Run the migration on its own
docker-db-migrate:
    docker compose -f local/docker-compose.yaml sdq-db-migration

# take down the docker stack, but also remove volumes
docker-clear-volumes:
    docker compose -f local/docker-compose.yaml down --volumes

# Connect a shell to the database.
connect-db:
    echo "Connecting to database"
    docker exec -it {{APPLICATION_NAME}}-db psql -d {{SDQ_DATABASE_NAME}} -U {{SDQ_DATABASE_USERNAME}}
