set dotenv-load := true

DB_MODULE := env_var("DB_MODULE")
APP_MODULE := env_var("APP_MODULE")
UI_MODULE := env_var("UI_MODULE")
APPLICATION_NAME := env_var("APPLICATION_NAME")
SDQ_DATABASE_NAME := env_var("SDQ_DATABASE_NAME")
SDQ_DATABASE_USERNAME := env_var("SDQ_DATABASE_USERNAME")

# Default task
default: run-dev

# Build the UI and Run the service via gradle
run-dev: copy-ui run-service-dev

# Build the application JAR file
build-jar: copy-ui
    ./gradlew :spring-app:bootJar

# Run the service via gradle
run-service-dev:
    ./gradlew :spring-app:bootRun

# Copy the static resources of the UI into the public backend folder.
copy-ui: build-ui
    rm -rf {{APP_MODULE}}/src/main/resources/static
    cp -R sdq-ui/dist {{APP_MODULE}}/src/main/resources/static

# Build the user interface
build-ui:
    npm run build --prefix {{UI_MODULE}}

# Runs the user interface in hot reloading mode.
run-ui-dev:
    npm run dev --prefix {{UI_MODULE}}

# Run the entire system up within Docker
docker-run-app: build-app-image build-db-migration-image
    docker compose -f local/docker-compose.yaml --profile include-service up

# Run the app dependencies in docker, but not the app itself
# Use run-service-dev for that
docker-run-deps: build-db-migration-image
    docker compose -f local/docker-compose.yaml up

# Stop any docker containers relating to this application
docker-stop:
    docker compose -f local/docker-compose.yaml down

# Build the Docker image for the application
build-app-image:
    docker build -t sdq-app .

# Build the Docker image for the database migration
build-db-migration-image:
    docker build -t sdq-db-migration {{DB_MODULE}}/.

# Run the database migration
build-db: build-db-migration-image
    docker compose -f {{DB_MODULE}}/docker-compose.yaml up

# Connect a shell to the database.
connect-db:
    echo "Connecting to database"
    docker exec -it {{APPLICATION_NAME}}-db psql -d {{SDQ_DATABASE_NAME}} -U {{SDQ_DATABASE_USERNAME}}
