spring:
  application:
    name: sdq-analysis
  security.oauth2.client:
    registration:
      keycloak:
        client-id: ${SDQ_CLIENT_ID}
        client-secret: ${SDQ_CLIENT_SECRET}
        scope: openid, profile, email
        authorization-grant-type: authorization_code
        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
    provider:
      keycloak:
        issuer-uri: ${OAUTH2_ISSUER_URI}

database:
  url: ${SDQ_DATABASE_URL}
  username: ${SDQ_DATABASE_USERNAME}
  password: ${SDQ_DATABASE_PASSWORD}