spring:
  application:
    name: sdq-analysis
  datasource:
    url: ${SDQ_DATABASE_URL}
    username: ${SDQ_DATABASE_USERNAME}
    password: ${SDQ_DATABASE_PASSWORD}
    hikari:
      leak-detection-threshold=5000:
